### ISSUE TITLE
The bots doesnt work anymore

### ISSUE THREAD

**Issue by Sulan2** [ineedbots/piw5_bot_warfare#100]
Since about a week ago the bots doesnt work, they are completely braindead in the game and do nothing pretty much.

Ive tried changing the difficulty setting but nothing happens

It worked like 1 week ago, I have auto update in Plutonium, how do I go back to an older version?

**Comment by ineedbots** [comment]
Please use v2.3.0 Bot Warfare

**Comment by Sulan2** [comment]
> Please use v2.3.0 Bot Warfare

Isnt this what Plutonium auto updates to?

**Comment by ineedbots** [comment]
you must manually update bot warfare as plutonium doesn't distribute bot warfare

**Comment by Sulan2** [comment]
> you must manually update bot warfare as plutonium doesn't distribute bot warfare

Ok I understand, thanks, it worked
