### ISSUE TITLE
How to rename bots? Missing bots.txt file in 2.3?

### ISSUE THREAD

**Issue by fellowboy** [ineedbots/piw5_bot_warfare#101]
Hello
Please advise on how to rename the bots, i see on previous version e.g. 2.1 that there was a bots.txt file you could edit.
Now that has gone

Thanks

**Comment by ineedbots** [comment]
all you need to do is place a `bots.txt` file inside of your `%LOCALAPPDATA%\Plutonium\storage\iw5` folder.

Each line is a possible bot name.
