### ISSUE TITLE
How to install the mod correctly

### ISSUE THREAD

**Issue by Tariqozoo** [ineedbots/piw5_bot_warfare#103]
1-How to install the mod correctly as this version lacks install.bat? I copied the whole mod file into mods in plutonium storage and enable it in game(is this correct?).
2-How to change the name of bots? this version seems different?
3-Is it me or the mod is not working on the latest version of IW5 even the older versions of the mod.

**Comment by ineedbots** [comment]
1. ![image](https://github.com/ineedbots/iw5_bot_warfare/assets/751729/2799b6d1-a838-4197-9938-67d325da2b75)
it has an install.bat? make sure to use the latest release .zip
2. same as before, you must put a `bots.txt` inside of your storage/iw5 folder.
3. you must you the latest bot warfare (v2.3.0+) with latest plutonium (r4047+)
