### ISSUE TITLE
[Crash] Dropzone doesn't appear to work

### ISSUE THREAD

**Issue by Master-64** [ineedbots/piw5_bot_warfare#107]
When loading into what seems like any map with the Dropzone gamemode, the game gets stuck on "Setting up game..." in the loading screen. The console spams a ton of code like this every frame:

```
cannot cast undefined to bool in a control statement

        at function "initfirstzone" in file "maps/mp/gametypes/grnd.gsc"
        at function "onstartgametype" in file "maps/mp/gametypes/grnd.gsc"
        at function "callback_startgametype" in file "maps/mp/gametypes/_gamelogic.gsc"
        at function "startgametypewithdev" in file "maps/mp/gametypes/_callbacksetup.gsc"
        at function "codecallback_startgametype" in file "maps/mp/gametypes/_callbacksetup.gsc"
```

**Comment by ineedbots** [comment]
![image](https://github.com/ineedbots/iw5_bot_warfare/assets/751729/8b25c604-be62-4329-8b61-e99c2ff0ae9d)
i can play just fine? do you have mods or something?

**Comment by ineedbots** [comment]
This is likely due to a custom map not support the gamemode.

**Comment by Master-64** [comment]
I've done further testing, turns out I just happened to pick a bunch of maps that all happened to not support Drop Zone, including Rust which I was assuming was fixed, but it wasn't. The issue isn't related with the mod, but the maps themselves. 👍
