### ISSUE TITLE
Exceeded maximum number of parent script variables after adding bots into the match.

### ISSUE THREAD

**Issue by NightmaREE3Z** [ineedbots/piw5_bot_warfare#108]
![image](https://github.com/ineedbots/iw5_bot_warfare/assets/132740635/e3718909-aed6-46bf-8a53-0d6126166edc)
Here you can see the message it crashes the game with. 
Worth to note, this happens with versions 2.20 and 2.30, but not with 2.10. On 2.10 I can do full 9v9 games, no issue. But on 2.20/2.30 it does this.

**Comment by ineedbots** [comment]
Are you on the latest plutonium update?

**Comment by ineedbots** [comment]
also, what map and gamemode?
![image](https://github.com/ineedbots/iw5_bot_warfare/assets/751729/19110e06-e2af-40c3-b247-b368c1f16081)

Hear i have added 17 just fine

**Comment by NightmaREE3Z** [comment]
I tried adding them on Domination, using Dome and Seatown as maps. 
And yes, I'm on 4.0.6.0. Even clean installed Plutonium just in case.

**Comment by ineedbots** [comment]
have you looked at #105    do you not have older files installed in localappdata/Plutonium/storage/iw5/scripts folder?

**Comment by NightmaREE3Z** [comment]
> have you looked at #105 do you not have older files installed in localappdata/Plutonium/storage/iw5/scripts folder?

Nvm, managed to get it to work (Atleast on my server) by clean installing whole MW3 and Plutonium. Then installing the mod as instructed. 

Thank you for your assist!
