### ISSUE TITLE
Bots are jerking around

### ISSUE THREAD

**Issue by kakahost** [ineedbots/piw5_bot_warfare#111]
They became extremely dumb. Enemies stand on one place and don't shoot, teammates doing... I dunno what are they doing, shooting walls and throwing grenades in them?

**Comment by ineedbots** [comment]
dupe of #109 make sure to remove any old bot warfare files

**Comment by kakahost** [comment]
Me and my friend have fresh MW3 install, same as fresh plutonium. We are both having this problem.

**Comment by kakahost** [comment]
And I checked for the old files, there's nothing.

**Comment by ineedbots** [comment]
make sure you are on the latest version of plutonium and bot warfare

**Comment by ineedbots** [comment]
dupe of #100
