### ISSUE TITLE
I don't know how to install it

### ISSUE THREAD

**Issue by Juanmaau** [ineedbots/piw5_bot_warfare#17]
I don't understand English very well and I don't really understand the installation tutorial, can someone explain it to me more simply? I have the MW3 from plutonium. Thanks

**Comment by whatcorey** [comment]
go on code and download as zip  inside the raw folder and copy "maps" and "scripts" folder to C:/Users/NAME/AppData/Local/Plutonium/iw5
Then open Plutonium and start Private match. Press N to open the mod menu of bot.  Dome and

**Comment by syaifulnizamyahya** [comment]
Is that folder correct? What about this folder, D:\Users\NAME\AppData\Local\Plutonium\storage\iw5

**Comment by ineedbots** [comment]
You'll see install instructions when a the mod is complete and sees a full release

**Comment by whatcorey** [comment]
> Is that folder correct? What about this folder, D:\Users\NAME\AppData\Local\Plutonium\storage\iw5

yes that will work

**Comment by ineedbots** [comment]
Added accurate instructions to the readme.md

**Comment by ineedbots** [comment]
https://github.com/ineedbots/piw5_bot_warfare/tree/master/out  will contain the files you will need

**Comment by whatcorey** [comment]
Thank you, but the damage.gsc file was removed and numbers remain popping out of enemies, how do I get rid of them?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
