### ISSUE TITLE
Numbers flying out of the sides of teammates and enemies when shooting them

### ISSUE THREAD

**Issue by whatcorey** [ineedbots/piw5_bot_warfare#18]
Whenever i shoot an enemy or teammate by accident, a bunch of numbers fly out of the sides of them, its really annoying. Last update did not have this problem. Is there any way to fix this? I prefer the original style where the number pops out after you kill them, not a bunch of numbers flying out of the sides every time they are shot.

**Comment by LeRutY** [comment]
It must be a debug thing, INeedGames probably forgot to remove it. It should be a optional thing but whatever. Here is the "fix": https://drive.google.com/file/d/1FccctOrsxeo5Vo7N8qphHZRR6h_osySq/view?usp=sharing I did that myself. Was looking at the commits and found "better print damage" and I edited the "damage.gsc" file and removed all added lines there. Drop the file into "maps\mp\gametypes"

**Comment by ineedbots** [comment]
This functionally will not be packaged with the mod when it is released, remove the _damage.gsc if you want it removed
