### ISSUE TITLE
Easy setting up a unbalanced match (3 vs 6 for example)

### ISSUE THREAD

**Issue by LeRutY** [ineedbots/piw5_bot_warfare#19]
Sry to put it here but I don´t really understand how to make a match 3 vs 6 (me with 2 bots vs 6 bots in the other team). I know how to do it in TDM but not in the side switching modes like in Domination because there the bots join my team after half-time. Would like to get a fourth menu tab for presets. Or add simple "Add x bots to allies / axis", "Remove x bots of allies /axis" options, so adjusting the amount doesn´t take a while. Currently it´s quite complex to get something else than balanced teams.

**Comment by LeRutY** [comment]
I think I have now understood how to get a proper 2 vs 4 for example. I still have questions: Where can I modify how difficult "veryhard" bots are? It´s done in the "_bot_script" file right? Also it is possible to have lower skilled bots in one team and higher skilled bots in the other team?

**Comment by ineedbots** [comment]
Use dvar `bots_skill` set to 8

![image](https://user-images.githubusercontent.com/751729/126835158-83414d3b-21f0-4aa5-8ce1-d040d1a09049.png)

**Comment by ineedbots** [comment]
Remember that bot warfare dvars are created in the context of a dedicated server, where there is no single main play, thats why it doesn't have a concept of bot_friends or bot_enemies

**Comment by LeRutY** [comment]
It makes sense that way, thx for explaining. I´ve got more questions: Can I change the bots behaviour in some ini file so they focus more on the objective in the respective modes? For example in "Capture the flag" the flag holding bot doesn´t take a direct route back to their own base. Or in "Domination" it often happens that bots near an enemy control point start to capture it but move away only to get back to it some time later. I´m someone who is playing the objective all the time  I have found a "wait time" in the _bot_script file, is that the right place?

Also what is the maximum amount of waypoints you´re accepting per map? "Liberation" and "Black Box" have the most waypoints, over 350. I´m noticing the game starts to lag with too many waypoints. Do you want me to remove some of the more unecessary waypoints?
