### ISSUE TITLE
[Feature Request] Standard IW5 support

### ISSUE THREAD

**Issue by nmjbhoffmann** [ineedbots/piw5_bot_warfare#2]
I'm sure you were expecting this request. But will this work with "standard" versions of the game, like the steam or the Project Nova mod or does this mod depend on Plutonium for its calls?

**Comment by ineedbots** [comment]
plutonium has several engine patches to make the bots work. the other projects do not have them and will not work with bot warfare

**Comment by nmjbhoffmann** [comment]
Figured as much, well, thanks for the reply, still appreciate the effort.
