### ISSUE TITLE
My waypoints for DLC maps

### ISSUE THREAD

**Issue by LeRutY** [ineedbots/piw5_bot_warfare#22]
I´m not sure if they´re any good (I´m quite skeptical). Aside from the normal waypoints, just a few with different stances on Liberation, Overwatch and Black Box, Only Piazza and Sanctuary have some additional grenade, noobtube and claymore waypoints currently. They´re all flag and bomb modes proof
[waypoints.zip](https://github.com/ineedbots/piw5_bot_warfare/files/6858119/waypoints.zip)

Here is the _bot_utility file
[_bot_utility.zip](https://github.com/ineedbots/piw5_bot_warfare/files/6842573/_bot_utility.zip)

**Comment by syaifulnizamyahya** [comment]
How do I install this waypoints?

**Comment by LeRutY** [comment]
For the "waypoints" file you have to go to "C:\Users\YourName\AppData\Local\Plutonium\storage\iw5\maps\mp\bots\waypoints"
and unzip it there. The "_bot_utility" has to be unzipped in the "bots" folder

**Comment by ineedbots** [comment]
pushed, thank you for your contribution

**Comment by LeRutY** [comment]
You´re more than welcome. I think about continuing my work, possibly also revising a few of the 5 maps I´ve added waypoints for (of course if no one gets ahead of me :D)
