### ISSUE TITLE
My waypoints for DLC maps fixed + Foundation and Erosion

### ISSUE THREAD

**Issue by LeRutY** [ineedbots/piw5_bot_warfare#23]
I have fixed major waypoint flaws on Piazza. Removed some waypoints in the spawn areas (let me know if that´s generally a good thing, imo yes). Foundation and Erosion can be played now. Bots can´t get up the ladder near the "Delta" spawn on Foundation though and I don´t know what´s wrong, so if someone can look into it, I would appreciate it. Also not many special waypoints on most maps 
[waypoints.zip](https://github.com/ineedbots/piw5_bot_warfare/files/6874712/waypoints.zip)
[_bot_utility.zip](https://github.com/ineedbots/piw5_bot_warfare/files/6874713/_bot_utility.zip)

**Comment by ineedbots** [comment]
pushed, thank you!
