### ISSUE TITLE
Questions about the mod

### ISSUE THREAD

**Issue by edustu** [ineedbots/piw5_bot_warfare#27]
First of all i'd like to say thank you very much for doing this job, it's been a blast to play it, seriously thank you very much.

I wanted to know if there is a way to disable the splash damage data in your hud (those numbers you get when you hit a bot)?

And is it possible to put more than 9 bots in just one side? I was looking forward to make like a 7x11 (me included), but as soon the enem team gets 9 bots it gets stuck and can't complete the team.

**Comment by LeRutY** [comment]
To answer the first question: Remove the "_damage.gsc" found at "C:\Users\YourName\AppData\Local\Plutonium\storage\iw5\maps\mp\gametypes"

**Comment by edustu** [comment]
Sry, but there is no "_damage.gsc" on "C:\Users\YourName\AppData\Local\Plutonium\storage\iw5\maps\mp\gametypes"

The only thing I foun is the "_class.gsc"
