### ISSUE TITLE
Hard bots too hard and med bots too easy

### ISSUE THREAD

**Issue by edustu** [ineedbots/piw5_bot_warfare#28]
It's not a big problem after all but, I think it should be perfect to set hard bot as the same reflexes and game sense but decreasing the headshot aimbot a bit, is it possible to set hard bots to hit only bodyshoots??

**Comment by LeRutY** [comment]
You can edit the "_bot_script.gsc" file (for me it´s in "C:\Users\YourName\AppData\Local\Plutonium\storage\iw5\maps\mp\bots"), look for "case", you will find case 1, case 2 and so on, those are the difficulty levels, 9 is the "random for all". There you can change the body parts, initital reaction time etc

**Comment by edustu** [comment]
Cool! thx for replying!
