### ISSUE TITLE
Implementing some random factors (Proning at Flag and Bomb Spots, shooting down killstreaks)

### ISSUE THREAD

**Issue by LeRutY** [ineedbots/piw5_bot_warfare#29]
If possible without the use of waypoints, bots could decide by some random chance to prone while capturing enemy flags (and eventually planting and defusing bombs). Or let them look or spin around

Second thing is about the bots shooting down killstreaks too fast. I´m suggesting a random (or fixed for each difficulty level) value (like elapsed time or after the x time of dying to the killstreak)

**Comment by ineedbots** [comment]
i have thought of doing this for awhile seeing the bo2 bots do this, it'll be on the todo list

**Comment by ineedbots** [comment]
Completed 521e31211e4508cdbd97592a8912a1a14d399104
