### ISSUE TITLE
Bots use custom default class 

### ISSUE THREAD

**Issue by ghostwulf** [ineedbots/piw5_bot_warfare#38]
It's possibile for bots use only your custom default classes?There is a command for this option?

**Comment by ineedbots** [comment]
set their level with `bots_loadout_rank` to below 4

**Comment by ghostwulf** [comment]
I tried to set bots_loadout_rank to 1,2 and 3 but bots use the standard default classes. I create a local recipe that contains my custom default classes and I load it, but bots don't use my custom default classes but only the standard default of MW3 (ex.ump45,mk46 and smaw striker and scorpion...). Is there a solution of this problem?

**Comment by ineedbots** [comment]
74d3e6877a338065a541d2433e53ecbf337bed43
