### ISSUE TITLE
Bots acting strange.

### ISSUE THREAD

**Issue by radioman2021** [ineedbots/piw5_bot_warfare#39]
For some reason, the bots during a match on either side of a team (during any mode). Will run/walk into a wall and jump repeatedly non-stop. (And become easy targets for other players/bots). On a few different maps like terminal, decommission, and possibly other maps as well. 

Am I the only one noticing this?

![Screenshot (17)](https://user-images.githubusercontent.com/89882281/133181938-ea02e46e-ef7e-4feb-8944-12bb312f21b3.png)
![Screenshot (21)](https://user-images.githubusercontent.com/89882281/133181942-c84f3a84-93b6-4641-8925-d70e265126fa.png)
![Screenshot (24)](https://user-images.githubusercontent.com/89882281/133181944-9b138353-e948-4150-a128-b636c85687aa.png)
![Screenshot (25)](https://user-images.githubusercontent.com/89882281/133181945-d58925f9-f6bf-4a2a-b5c4-ec18155f88e2.png)

**Comment by radioman2021** [comment]
> For some reason, the bots during a match on either side of a team (during any mode). Will run/walk into a wall and jump repeatedly non-stop. (And become easy targets for other players/bots). On a few different maps like terminal, decommission, and possibly other maps as well.
> 
> Am I the only one noticing this?
> 
> ![Screenshot (17)](https://user-images.githubusercontent.com/89882281/133181938-ea02e46e-ef7e-4feb-8944-12bb312f21b3.png)
> ![Screenshot (21)](https://user-images.githubusercontent.com/89882281/133181942-c84f3a84-93b6-4641-8925-d70e265126fa.png)
> ![Screenshot (24)](https://user-images.githubusercontent.com/89882281/133181944-9b138353-e948-4150-a128-b636c85687aa.png)
> ![Screenshot (25)](https://user-images.githubusercontent.com/89882281/133181945-d58925f9-f6bf-4a2a-b5c4-ec18155f88e2.png)



> For some reason, the bots during a match on either side of a team (during any mode). Will run/walk into a wall and jump repeatedly non-stop. (And become easy targets for other players/bots). On a few different maps like terminal, decommission, and possibly other maps as well.
> 
> Am I the only one noticing this?
> 
> ![Screenshot (17)](https://user-images.githubusercontent.com/89882281/133181938-ea02e46e-ef7e-4feb-8944-12bb312f21b3.png)
> ![Screenshot (21)](https://user-images.githubusercontent.com/89882281/133181942-c84f3a84-93b6-4641-8925-d70e265126fa.png)
> ![Screenshot (24)](https://user-images.githubusercontent.com/89882281/133181944-9b138353-e948-4150-a128-b636c85687aa.png)
> ![Screenshot (25)](https://user-images.githubusercontent.com/89882281/133181945-d58925f9-f6bf-4a2a-b5c4-ec18155f88e2.png)

**Comment by ineedbots** [comment]
waypoint issue, make sure that the waypoints for terminal are being loaded

**Comment by radioman2021** [comment]
Oh ok, I noticed this issue on a few other maps. But I will see how to fix them.
