### ISSUE TITLE
Bots getting stuck occasionally where they didn't before

### ISSUE THREAD

**Issue by GaryTheNoTrashCougar** [ineedbots/piw5_bot_warfare#43]
I believe this may have something to do with a recent plutonium update.  I haven't played this in a while, but there wasn't any issues with bots getting stuck last time I played (not sure how long ago but probably 1-2 months ago).  I didn't initially update the mod when I started playing again but when I did, it was still happening.  Maps have waypoints & they don't lead through objects the bots are getting stuck on.

**Comment by ineedbots** [comment]
most likely caused by the sprint changes, will not fix.

better fix is to detect when the bot is stuck more quicker
