### ISSUE TITLE
Bot stuck deploying killstreaks at invalid map locations, does not moveaway unless killed.

### ISSUE THREAD

**Issue by Shepherddidnothingwrong** [ineedbots/piw5_bot_warfare#47]
The screenshot is from Oasis, but this also happened on Boardwalk at the dumpster where you can climb up. Not sure if this a waypoint issue as I also seen it happened on some other maps too, but not as frequent.  

![bot stuck](https://user-images.githubusercontent.com/89765049/140240078-9ec4f360-dda2-4481-bb10-079044136cd3.png)

**Comment by ineedbots** [comment]
waypoint issue, discuss at #6
