### ISSUE TITLE
Can't load waypoints in waypoint editor

### ISSUE THREAD

**Issue by GaryTheNoTrashCougar** [ineedbots/piw5_bot_warfare#50]
Waypoint editor not loading saved waypoints, possibly due to incorrect file pathing in load_waypoints function?

I wanted to try & fix some of the waypoints where bots are getting stuck on respawn.
Seems the bots tend to go for the nearest waypoint when spawning, which sometimes is not accessible.  Not sure if there is a way to highlight spawn locations within the editor in order to create appropriate waypoints or maybe you posses the skills to write a function that does such a thing?

**Comment by GaryTheNoTrashCougar** [comment]
Work around - pasting a maps waypoints into 'maps\mp\bots\waypoints\_custom_map.gsc'

**Comment by ineedbots** [comment]
Fixed in 5e7eb2fc17a9deb66316ba3a101aa9f005bbdcfb
