### ISSUE TITLE
Not a problem, just a question: How to make bots dropshot more often?

### ISSUE THREAD

**Issue by edustu** [ineedbots/piw5_bot_warfare#52]
I'm aware of the bot_script folder, I just don't know wich variable affects dropshooting, is it one of these?

			self.pers["bots"]["behavior"]["strafe"] = 50;
			self.pers["bots"]["behavior"]["nade"] = 45;
			self.pers["bots"]["behavior"]["sprint"] = 65;
			self.pers["bots"]["behavior"]["camp"] = 5;
			self.pers["bots"]["behavior"]["follow"] = 5;
			self.pers["bots"]["behavior"]["crouch"] = 10;
			self.pers["bots"]["behavior"]["switch"] = 2;
			self.pers["bots"]["behavior"]["class"] = 2;
			self.pers["bots"]["behavior"]["jump"] = 75;

**Comment by edustu** [comment]
Oh, I see it now, it is    self.pers["bots"]["behavior"]["jump"]    , but what if I change the strafe percentage to 100, does it mean that bots will always strafe therefore they will no longer be able to dropshot??

**Comment by ineedbots** [comment]
You found what you are looking for, this'll be done by modifying those values
