### ISSUE TITLE
Not an Issue just a question: How to change loadouts for bots?

### ISSUE THREAD

**Issue by ElijahThaddius** [ineedbots/piw5_bot_warfare#53]
Hi, 

To start, I just want to say that I really appreciate the effort you have all put into these bot mods. They are fantastic.

I am playing around with the mods for my custom server, and I have not had much luck finding out how to set the loadouts for the bots. I am trying to create a snipers only bot lobby and am having some difficulty. Is there a way to filter the weapons that a bot chooses for a loadout? Or is there a way to force a bot to choose the default loadouts/ follow the restrictions of the custom game mode. 

Any help would be appreciated. 

Thankyou!

**Comment by ineedbots** [comment]
Through the use of mods

IW4x example
https://github.com/ineedbots/iw4x_bot_warfare/blob/master/userraw/scripts/bots_sniper_loadout.gsc#L29
