### ISSUE TITLE
Private Match Post Match Summary Crash to Desktop

### ISSUE THREAD

**Issue by Bookcollector1** [ineedbots/piw5_bot_warfare#54]
When in a Private Match with Bots, upon completion of a round a Kill summary is displayed.
When you press Continue, the game crashes to the desktop rather than returning to main menu

**Comment by Aesirix** [comment]
The crashing bug with the Private Match Summary is a Plutonium bug, not the
bot mod. :)

**Comment by PureAnarchy** [comment]
Where did you download the mod? There's no release on the releases page.

**Comment by PureAnarchy** [comment]
> Where did you download the mod? There's no release on the releases page.

Nevermind, I'm stupid. I figured it out. For anyone else lost, click on the "CODE" button in the upper right, then "Download ZIP".

**Comment by knifes12** [comment]
Just press ECS to stop it.
Dont click continue

**Comment by ineedbots** [comment]
dupe #26
