### ISSUE TITLE
How to change bot names? Where's the bots.txt file supposed to be?

### ISSUE THREAD

**Issue by GhendraNova** [ineedbots/piw5_bot_warfare#55]
Everything is in the title. I've checked everywhere in both my steam files and plutonium files and can't seem to find the bots.txt.

**Comment by GaryTheNoTrashCougar** [comment]
C:\Users\ -Your User Name - \AppData\Local\Plutonium\storage\iw5
[bots.txt](https://github.com/ineedbots/piw5_bot_warfare/files/8227526/bots.txt)
