### ISSUE TITLE
Issues with bomb interactions

### ISSUE THREAD

**Issue by bermudaswampus** [ineedbots/piw5_bot_warfare#61]
In my experience, these bots work really well outside of 1 issue, which is that they don't properly interact with the bomb in demolition. They do go after the bomb, but after interacting with it to plant or defuse for half a second, they just stop and take their gun back out. I'm not sure if its something on my end with installation or an issue with the bots.

Heres a video of me watching the bots around the bomb - https://www.youtube.com/watch?v=xaFfog02hio

**Comment by ineedbots** [comment]
thanks for catching this, fixed 9be5b7e612d0cfdd83761ae1c00da7c3dcf378da
