### ISSUE TITLE
bots are so op from long distances

### ISSUE THREAD

**Issue by Tariqozoo** [ineedbots/piw5_bot_warfare#62]
Bots are so OP from long distance, can you nerf them by a little? Because it's impossible to win a gunfight against bots from long distances, onetime a bot killed me with a headshot from the end of the map with mp-9 can you imagine  MP-9!!! no way.

**Comment by TheOreoSlayer** [comment]
You can manually edit this in the bots script

**Comment by Tariqozoo** [comment]
I know I'm an idiot but can you show me how?

**Comment by ineedbots** [comment]
dupe #59
