### ISSUE TITLE
scavenger perk broken?

### ISSUE THREAD

**Issue by theminecraften66** [ineedbots/piw5_bot_warfare#64]
when i equip the non pro version of scavenger i get the benifit of scavenger pro without having it unlocked. just wondering if this is a problem with bot warfare or with plutonim itself.

**Comment by ineedbots** [comment]
plutonium related, not mod.

**Comment by CrazyCSIW6** [comment]
Are you sure?
I had a Plutonium Discord mod say to me, and I quote "We don't force pro perks".
Is there something we're missing?
