### ISSUE TITLE
crash error exceded maximum number of child1 scripts?

### ISSUE THREAD

**Issue by theminecraften66** [ineedbots/piw5_bot_warfare#65]
have no idea what this crash is but was going to ask if its mod related or if i should be asking about it on the plutoniom fourms.

**Comment by ineedbots** [comment]
when? where? i need more context, what map, how many bots, gamemode, etc.

**Comment by Tariqozoo** [comment]
![Screenshot 2022-05-16 170505](https://user-images.githubusercontent.com/104523704/168611330-f1c4341d-7e12-45e6-a432-e2d669a64bb3.png)

**Comment by Tariqozoo** [comment]
Make sure that you have the last version of the mod
