### ISSUE TITLE
Setting bot rank seems to be hit and miss.

### ISSUE THREAD

**Issue by tobi-polar** [ineedbots/piw5_bot_warfare#70]
I set bots to prestige 0 rank 80, but they don't all appear as rank 80, some being in the 70's. This on on a dedicated server.

`set bots_loadout_rank "80"`
`set bots_loadout_prestige "0"`

![20220604115245_1](https://user-images.githubusercontent.com/36657224/171972168-3b207ade-b245-4e81-bbcd-572ea5dc3af3.jpg)

**Comment by Aesirix** [comment]
I'm not 100% certain how it calculates rank, but I think since you put 80 it's choosing ranks around 80. Makes me wonder if choosing something like 90 would make it so that they are all 80.
