### ISSUE TITLE
Crashes upon finishing a match and trying to start a new one

### ISSUE THREAD

**Issue by AlexWingace** [ineedbots/piw5_bot_warfare#76]
When you finish a Private Match, it boots you to the main multiplayer menu. If you click on Private Match again, the game crashes. It's happened every time now, and I don't think I missed any steps in the installation. Otherwise, the bots seem to work as intended. A friend of mine is reporting the same issue.

Here's the crash logs, if that'll help. 

[plutonium-r3266-iw5mp-2022-08-31_04-50-25.txt](https://github.com/ineedbots/piw5_bot_warfare/files/9465036/plutonium-r3266-iw5mp-2022-08-31_04-50-25.txt)
[plutonium-r3266-iw5mp-2022-08-31_05-06-22.txt](https://github.com/ineedbots/piw5_bot_warfare/files/9465037/plutonium-r3266-iw5mp-2022-08-31_05-06-22.txt)
[plutonium-r3266-iw5mp-2022-08-31_04-35-06.txt](https://github.com/ineedbots/piw5_bot_warfare/files/9465038/plutonium-r3266-iw5mp-2022-08-31_04-35-06.txt)

**Comment by Juggernaut369** [comment]
If it crashes as soon as you click private match this won’t help, but if you make it to the next screen where it shows the score/results from the last match, don’t hit continue. For whatever reason hitting continue crashes every time. Hit escape, and it should advance without crashing.

**Comment by AlexWingace** [comment]
Yeah, after several hours of looking, I found this workaround, which has apparently been a running issue on Plutonium that's gone unfixed for over a month.

Thank you though. Maybe anyone else having this issue will find this thread for the answer they need.
