### ISSUE TITLE
Having more than 30 waypoints cases in load_waypoints() crashes the game

### ISSUE THREAD

**Issue by Resxt** [ineedbots/piw5_bot_warfare#78]
Hello,

I was recently setting up my servers when suddenly my game started crashing every time I clicked on "Start match" (in private match) no matter which map or mode I picked.

I tested half of the base game maps, some DLC maps, some Plutonium maps and some custom maps I had and they were all crashing in the load screen.

I spent hours trying to find what could be causing this so I re-did a clean installation of Plutonium, re-added things one by one and tried each time. It only crashed when I re-added my 32 cases in the `load_waypoints()` switch case found in `maps\mp\bots\waypoints\`

I attached my waypoints folder and my `_bot_utility.gsc` files [here ](https://drive.proton.me/urls/XWJRAJBNJW#qnk9GzivUYtW)so you can have a look.
Apart from the default case it has 31 cases. If you remove any of them, no matter which one it won't crash anymore since you will be at 30. If you try again by adding one or two cases you will see it crashes again.

After testing for a moment it seems that having more than 30 cases causes the game to crash in the loadscreen.
"Out of memory error. You are probably low on hard disk space"

![image](https://user-images.githubusercontent.com/55228336/189492860-6feef537-40ae-4c9a-89cd-da0af15db413.png)

Please let me know if I can help you in away.
I love Bot Warfare and I have more than 30 custom maps and would love to use them all with bots using working waypoints, thanks!

**Comment by ineedbots** [comment]
Engine issue, its trying to compile all the waypoint gsc at once for each map. There isn't many free gsc scripts left.

Use the new way of loading waypoints: https://github.com/ineedbots/piw5_bot_warfare/tree/master/raw/scripts/mp
