### ISSUE TITLE
Game crashes when navigating the Create a Class screen.

### ISSUE THREAD

**Issue by koopa990** [ineedbots/piw5_bot_warfare#80]
Often enough, the game stops working when I click on the sub menus of "create a class". Who else have this problem? If so, Why has no one reported it?

**Comment by koopa990** [comment]
Exception Code: 0xC00000FD
Exception Address: 0x00733507

**Comment by ineedbots** [comment]
client related, not mod related

**Comment by koopa990** [comment]
> 

Alright, thanks. It was the client
