### ISSUE TITLE
Can't rename bots

### ISSUE THREAD

**Issue by LaykaKiro** [ineedbots/piw5_bot_warfare#84]
How do I do it?

**Comment by EricTurner3** [comment]
Navigate to your `C:\Users\<user>\AppData\Local\Plutonium\storage\iw5` folder.  There should be a `z_svr_bots.iwd` file here. Open it with 7Zip or WinRAR. Inside of this archive is a bots.txt file. Replace the a-z characters with as many names that you wish.

Here is a sample list:

> BFG_Guy_93
Duke Nukem
BorgCollective
CullingCard
TheFinalCountdown
SeekNDstroy
Bulletz4Breakfast
BigDamnHero
LaidtoRest
IronMAN77
Xenomorphing
TylerDurden
Rust_in_Pieces
PennywiseTheClown
BluntMachete
SniperLyfe
SilentWraith
Ranger & Co.
BloodyAssault
FightClubAlum
KillSwitch
ExecuteElectrocute
BadBaneCat
IndominusRexxx
AzogtheDefiler
BitchWhoDontMiss
FlameThrower951
PistolPrincess86
Termin8tor
K3yboardK1ng
LightningFist
BadSoldier
BoringP3rson
DevilDriver
MrSn1p3rHead
HeadHunterz
PsyOpsNinja
ClutchG4mer
TheGreenHulk
BladeRunnerX
H3llR4z3r
VoltageWarrior
MegaD3stroyer
TheK1ngSlayer
BionicWarrior
PixelMast3r
SubZer0Fury
GlitteryD3vil
Unholy Trinity
The Dark Knight
Evil Genius
Master Of Disaster
Death Warrant
Nuclear Winter
R1de_L1ghtning
Dead On Arrival
Cold Blooded
Soulless
The Grim Reaper
Bringer Of Death
Killers
Lord Of Darkness
Prince Of Evil
DevilzAdvocate
Bad Soldier
A bad cold
Tortured Soul
Prince Of Lies
Powerslave
Netflix and Kill
DeathShadow
ChaosKing
Black Magician
Evil Genius
The Bong King
Skull Trooper
Psycho Killer
Dragonborn
Rider Of Light
Forger Of Souls
The Dark Knight
The White Wolf
Warden Of Light
BoysVodka
Duskbringer
The Night King
Bringer Of Storms
Frostmourne
TheIce Man
Ruler Of Hell
Lone Wolf
Sp1nal_T@p_84
Shadow Caster
Dragon Slayer
Loading...
Black Knight
Sirius
The Great One
Thunder Struck
Xenomorph
ZombieKiller
Eternal Warrior
King Of Battle
God of Warfare
Son Of Mars
Master Of Puppets
Prince Of Darkness
Demon Hunter
BuffyDaSlaya
Angelus
Angel_of_Deth
Soldier of Fortune
Norse God of War
Mercenary King
Nemesis Prime
Red Devil
Blue Thunder
Green Lantern
Back in Hack
Looks that Kill
KillBill
Spiderman
A light Breeze
the_G0D_K1ng
666_SLAYER_666

**Comment by LaykaKiro** [comment]
Oh I forgot I made this post. I already figured it out alone a bit ago. Thanks for the info anyway.
