### ISSUE TITLE
Game Crash after calling in MOAB

### ISSUE THREAD

**Issue by SteelBite** [ineedbots/piw5_bot_warfare#85]
My came crashes and i get a error code looking like this
![Screenshot 2023-04-10 115618](https://user-images.githubusercontent.com/20042678/230810265-7cac4397-b881-4437-974b-7e44f57463d7.png)

**Comment by SteelBite** [comment]
I believe im missing files, from what i can see but i cannot find any solution to replacing the files or what to do

**Comment by diamante0018** [comment]
@ineedbots
