### ISSUE TITLE
Bot Chat Not Working

### ISSUE THREAD

**Issue by EricTurner3** [ineedbots/piw5_bot_warfare#86]
The bot chatter does not seem to be working at all. I modified the `self sayteam` and `self sayall` functions in the _bots_chat.gsc file to `say` and chat did start populating as [Server]. It doesn't seem like `self sayall` is working properly.

**Comment by diamante0018** [comment]
@ineedbots

**Comment by ineedbots** [comment]
this was fixed on plutonium's side
