### ISSUE TITLE
Loading game

### ISSUE THREAD

**Issue by Juliencuistot** [ineedbots/piw5_bot_warfare#88]
Okay when I lunch the game in private server (so I can play aginst bot alone) It load but after some second it bring me back to the menu telling me this : [error]:compiler:maps/mp/bots/_bot_utility.gsc:780:1: fuction name 'float' already defined as builtin.
but I don't understand what do I have to do.
so my frist intention was to delete the bot... so I did but got another message that tell the same but another bot thing so I deleted them all and not work but after I got back to the site dowloaded the new one added it to bots but still don't work and get the same Message. 
could you guys tell me what to do or help me please cause I can't play the game against bot anymore

**Comment by skeletonsx** [comment]
I'm having the same problem lately, and i played more than 100+ matches without a problem, i really hope there is a fix for this.

**Comment by Resxt** [comment]
@Juliencuistot @skeletonsx 

Long story short Plutonium "introduced a bug" with its new version and the latest release of Bot Warfare was made before this.
BUT Bot Warfare already fixed the issue some time ago, it's just not released as a user download release basically.

Simply downloading the .iwd file manually and replacing yours will fix the error
Direct download link: https://raw.githubusercontent.com/ineedbots/piw5_bot_warfare/master/out/z_svr_bots.iwd
Install: place the file in `%localappdata%\Plutonium\storage\iw5` and replace it. Of course backup the content of the existing file if you added anything like waypoints or modified bot names etc

**Comment by skeletonsx** [comment]
> @Juliencuistot @skeletonsx
> 
> Long story short Plutonium "introduced a bug" with its new version and the latest release of Bot Warfare was made before this. BUT Bot Warfare already fixed the issue some time ago, it's just not released as a user download release basically.
> 
> Simply downloading the .iwd file manually and replacing yours will fix the error Direct download link: https://raw.githubusercontent.com/ineedbots/piw5_bot_warfare/master/out/z_svr_bots.iwd Install: place the file in `%localappdata%\Plutonium\storage\iw5` and replace it. Of course backup the content of the existing file if you added anything like waypoints or modified bot names etc

Thank you a lot!, it worked for me, and now even the bot's chat is working, thank you very much.

**Comment by Juliencuistot** [comment]
> @Juliencuistot @skeletonsx
> 
> Long story short Plutonium "introduced a bug" with its new version and the latest release of Bot Warfare was made before this. BUT Bot Warfare already fixed the issue some time ago, it's just not released as a user download release basically.
> 
> Simply downloading the .iwd file manually and replacing yours will fix the error Direct download link: https://raw.githubusercontent.com/ineedbots/piw5_bot_warfare/master/out/z_svr_bots.iwd Install: place the file in `%localappdata%\Plutonium\storage\iw5` and replace it. Of course backup the content of the existing file if you added anything like waypoints or modified bot names etc

thanks bro so much I can finally play against bot after weeks of just doing shit
