### ISSUE TITLE
Compile Error (screenshot)

### ISSUE THREAD

**Issue by koopa990** [ineedbots/piw5_bot_warfare#90]
something about Bot_Utility.gsc.
I cannot send pic for further details.

**Comment by koopa990** [comment]
gsc:780:1:function name Float already defined as builitin

**Comment by SRC267** [comment]
Happens to one of my PC's my other PC doesn't encounter this. Both updated clients, too.

**Comment by Resxt** [comment]
@koopa990 @SRC267 
https://github.com/ineedbots/piw5_bot_warfare/issues/88#issuecomment-1551419606
