### ISSUE TITLE
not being able to change bot names with new update?

### ISSUE THREAD

**Issue by theminecraften66** [ineedbots/piw5_bot_warfare#96]
not a big deal just a fun QOL option you added to the first release but you seem to have taken it out with the new update. it was just something to name the bots to make the mod feel more like a online match.  just would be a nice QOL update for the mod to be able to edit the text file to rename the bots

**Comment by ineedbots** [comment]
place your `bots.txt` inside of `%LOCALAPPDATA%\Plutonium\storage\iw5`

inside of your bots.txt file; each line will be a bot name, optionally you can add a clantag by adding a comma after the name and then the clantag after it
