### ISSUE TITLE
updating mod poblem

### ISSUE THREAD

**Issue by tiger710c** [ineedbots/piw5_bot_warfare#99]
when i upgrade my version to a newer one it gives me this error:
Com_ERROR: [ERROR]:compiler:scripts/mp/bots_adapter_piw5.gsc:59:7: couldn't determine function call type

**Comment by ineedbots** [comment]
I dont get no such error, Make sure you are on the latest update of plutonium

**Comment by tiger710c** [comment]
yeah it was that lmfao my bad
